// ⚙️ Auto-generated. Edit only the "meta" fields below.
import { lazy } from "react";
 
const ROUTES = {
	SIGNIN: {
    component: lazy(() => import("@pages/SignIn")),
    url: "/signin",
    paths: ["/SignIn"],
    order: 0,
		title: "로그인",
		noLayout: true,
  },
	PASSWORD: {
    component: lazy(() => import("@pages/Password")),
    url: "/password",
    paths: ["/Password"],
    order: 1,
		title: "비밀번호 변경",
  },
	DASHBOARD: {
    component: lazy(() => import("@pages/Dashboard")),
    url: "/dashboard",
    paths: ["/Dashboard"],
    order: 10,
		title: "대시보드",
  },
	ROBOT_LIST: {
    component: lazy(() => import("@pages/robot/List")),
    url: "/robot/list",
    paths: ["/robot", "/List"],
    order: 2000,
		title: "로봇",
  },
	ROBOT_DETAIL: {
    component: lazy(() => import("@pages/robot/Detail")),
    url: "/robot/detail",
    paths: ["/robot", "/Detail"],
    order: 2100,
		title: "로봇_상세 정보",
  },
	ASSIGNMENT_INFO_LIST: {
    component: lazy(() => import("@pages/assignment/info/List")),
    url: "/assignment/info/list",
    paths: ["/assignment", "/info", "/List"],
    order: 3100,
		title: "과제관리_수행업무정보",
  },
	ASSIGNMENT_APPLICATION_LIST: {
    component: lazy(() => import("@pages/assignment/application/List")),
    url: "/assignment/application/list",
    paths: ["/assignment", "/application", "/List"],
    order: 3200,
		title: "과제관리_업무신청",
  },
	ASSIGNMENT_APPLICATION_REG: {
    component: lazy(() => import("@pages/assignment/application/Reg")),
    url: "/assignment/application/reg",
    paths: ["/assignment", "/application", "/Reg"],
    order: 3201,
		title: "과제관리_업무신청_신규개발 신청",
  },
	EXECUTION_ASSIGNMENT_LIST: {
    component: lazy(() => import("@pages/execution/assignment/List")),
    url: "/execution/assignment/list",
    paths: ["/execution", "/assignment", "/List"],
    order: 4100,
		title: "수행관리_업무할당",
  },
	EXECUTION_CALENDAR_LIST: {
    component: lazy(() => import("@pages/execution/calendar/List")),
    url: "/execution/calendar/list",
    paths: ["/execution", "/calendar", "/List"],
    order: 4200,
		title: "수행관리_업무캘린더",
  },
	EXECUTION_QUEUE_LIST: {
    component: lazy(() => import("@pages/execution/queue/List")),
    url: "/execution/queue/list",
    paths: ["/execution", "/queue", "/List"],
    order: 4300,
		title: "수행관리_업무대기열",
  },
	EXECUTION_RESULT_RESULTS_LIST: {
    component: lazy(() => import("@pages/execution/result/results/List")),
    url: "/execution/result/results/list",
    paths: ["/execution", "/result", "/results", "/List"],
    order: 4410,
		title: "수행관리_업무실행결과_업무 실행 결과 내역",
  },
	EXECUTION_RESULT_ROBOTS_LIST: {
    component: lazy(() => import("@pages/execution/result/robots/List")),
    url: "/execution/result/robots/list",
    paths: ["/execution", "/result", "/robots", "/List"],
    order: 4420,
		title: "수행관리_업무실행결과_업무 실행 로봇별",
  },
	EXECUTION_RESULT_WORKS_LIST: {
    component: lazy(() => import("@pages/execution/result/works/List")),
    url: "/execution/result/works/list",
    paths: ["/execution", "/result", "/works", "/List"],
    order: 4430,
		title: "수행관리_업무실행결과_업무별 누적",
  },
	EXECUTION_FILE_LIST: {
    component: lazy(() => import("@pages/execution/file/List")),
    url: "/execution/file/list",
    paths: ["/execution", "/file", "/List"],
    order: 4500,
		title: "수행관리_수행파일업로드",
  },
	EXECUTION_PERFORMANCE_LIST: {
    component: lazy(() => import("@pages/execution/performance/List")),
    url: "/execution/performance/list",
    paths: ["/execution", "/performance", "/List"],
    order: 4600,
		title: "수행관리_실적관리",
  },
	PROCESS_LIST: {
    component: lazy(() => import("@pages/process/List")),
    url: "/process/list",
    paths: ["/process", "/List"],
    order: 5000,
		title: "프로세스",
  },
	PACKAGE_LIST: {
    component: lazy(() => import("@pages/package/List")),
    url: "/package/list",
    paths: ["/package", "/List"],
    order: 6000,
		title: "패키지",
  },
	LOG_PACKAGE_LIST: {
    component: lazy(() => import("@pages/log/package/List")),
    url: "/log/package/list",
    paths: ["/log", "/package", "/List"],
    order: 7100,
		title: "로그_ 패키지 로그",
  },
	LOG_ROBOT_LIST: {
    component: lazy(() => import("@pages/log/robot/List")),
    url: "/log/robot/list",
    paths: ["/log", "/robot", "/List"],
    order: 7200,
		title: "로그_로봇 로그",
  },
	LOG_WORK_LIST: {
    component: lazy(() => import("@pages/log/work/List")),
    url: "/log/work/list",
    paths: ["/log", "/work", "/List"],
    order: 7300,
		title: "로그_업무 로그",
  },
	LOG_QUEUE_LIST: {
    component: lazy(() => import("@pages/log/queue/List")),
    url: "/log/queue/list",
    paths: ["/log", "/queue", "/List"],
    order: 7400,
		title: "로그_데이터 큐 로그",
  },
	LOG_STUDIO_LIST: {
    component: lazy(() => import("@pages/log/studio/List")),
    url: "/log/studio/list",
    paths: ["/log", "/studio", "/List"],
    order: 7500,
		title: "로그_스튜디오 로그",
  },
	LOG_PORTAL_LIST: {
    component: lazy(() => import("@pages/log/portal/List")),
    url: "/log/portal/list",
    paths: ["/log", "/portal", "/List"],
    order: 7600,
		title: "로그_포탈 로그",
  },
	PBLRESOURCE_VARIABLE_LIST: {
    component: lazy(() => import("@pages/pblresource/variable/List")),
    url: "/pblresource/variable/list",
    paths: ["/pblresource", "/variable", "/List"],
    order: 8100,
		title: "공용 리소스_공용 변수",
  },
	PBLRESOURCE_FILE_LIST: {
    component: lazy(() => import("@pages/pblresource/file/List")),
    url: "/pblresource/file/list",
    paths: ["/pblresource", "/file", "/List"],
    order: 8110,
		title: "공용 리소스_공용 파일",
  },
	PBLRESOURCE_SHARELIB_LIST: {
    component: lazy(() => import("@pages/pblresource/sharelib/List")),
    url: "/pblresource/sharelib/list",
    paths: ["/pblresource", "/sharelib", "/List"],
    order: 8110,
		title: "공용 리소스_공유 라이브러리",
  },
	QUEUE_LIST: {
    component: lazy(() => import("@pages/queue/List")),
    url: "/queue/list",
    paths: ["/queue", "/List"],
    order: 9000,
		title: "데이터 큐",
  },
	COMMUNITY_INCIDENT_LIST: {
    component: lazy(() => import("@pages/community/incident/List")),
    url: "/community/incident/list",
    paths: ["/community", "/incident", "/List"],
    order: 10100,
		title: "커뮤니티_장애관리",
  },
	COMMUNITY_INCIDENT_REG: {
    component: lazy(() => import("@pages/community/incident/Reg")),
    url: "/community/incident/reg",
    paths: ["/community", "/incident", "/Reg"],
    order: 10101,
		title: "커뮤니티_장애관리_등록",
  },
	COMMUNITY_INCIDENT_EDIT: {
    component: lazy(() => import("@pages/community/incident/Edit")),
    url: "/community/incident/edit",
    paths: ["/community", "/incident", "/Edit"],
    order: 10102,
		title: "커뮤니티_장애관리_수정",
  },
	COMMUNITY_INCIDENT_DETAIL: {
    component: lazy(() => import("@pages/community/incident/Detail")),
    url: "/community/incident/detail",
    paths: ["/community", "/incident", "/Detail"],
    order: 10103,
		title: "커뮤니티_장애관리_상세",
  },
	COMMUNITY_NOTICE_LIST: {
    component: lazy(() => import("@pages/community/notice/List")),
    url: "/community/notice/list",
    paths: ["/community", "/notice", "/List"],
    order: 10200,
		title: "커뮤니티_공지사항",
  },
	COMMUNITY_NOTICE_REG: {
    component: lazy(() => import("@pages/community/notice/Reg")),
    url: "/community/notice/reg",
    paths: ["/community", "/notice", "/Reg"],
    order: 10201,
		title: "커뮤니티_공지사항_등록",
  },
	COMMUNITY_NOTICE_EDIT: {
    component: lazy(() => import("@pages/community/notice/Edit")),
    url: "/community/notice/edit",
    paths: ["/community", "/notice", "/Edit"],
    order: 10202,
		title: "커뮤니티_공지사항_수정",
  },
	COMMUNITY_FAQ_LIST: {
    component: lazy(() => import("@pages/community/faq/List")),
    url: "/community/faq/list",
    paths: ["/community", "/faq", "/List"],
    order: 10300,
		title: "커뮤니티_FAQ",
  },
	COMMUNITY_FAQ_REG: {
    component: lazy(() => import("@pages/community/faq/Reg")),
    url: "/community/faq/reg",
    paths: ["/community", "/faq", "/Reg"],
    order: 10301,
		title: "커뮤니티_FAQ_등록",
  },
	COMMUNITY_FAQ_EDIT: {
    component: lazy(() => import("@pages/community/faq/Edit")),
    url: "/community/faq/edit",
    paths: ["/community", "/faq", "/Edit"],
    order: 10302,
		title: "커뮤니티_FAQ_수정",
  },
	COMMUNITY_BOARD_LIST: {
    component: lazy(() => import("@pages/community/board/List")),
    url: "/community/board/list",
    paths: ["/community", "/board", "/List"],
    order: 10400,
		title: "커뮤니티_게시판",
  },
	COMMUNITY_BOARD_REG: {
    component: lazy(() => import("@pages/community/board/Reg")),
    url: "/community/board/reg",
    paths: ["/community", "/board", "/Reg"],
    order: 10401,
		title: "커뮤니티_게시판_등록",
  },
	COMMUNITY_DOC_LIST: {
    component: lazy(() => import("@pages/community/doc/List")),
    url: "/community/doc/list",
    paths: ["/community", "/doc", "/List"],
    order: 10500,
		title: "커뮤니티_자료실",
  },
	COMMUNITY_DOC_REG: {
    component: lazy(() => import("@pages/community/doc/Reg")),
    url: "/community/doc/reg",
    paths: ["/community", "/doc", "/Reg"],
    order: 10501,
		title: "커뮤니티_자료실_등록",
  },
	COMMUNITY_BOT_LIST: {
    component: lazy(() => import("@pages/community/bot/List")),
    url: "/community/bot/list",
    paths: ["/community", "/bot", "/List"],
    order: 10600,
		title: "커뮤니티_체험봇 신청",
  },
	COMMUNITY_TEMPLATE_LIST: {
    component: lazy(() => import("@pages/community/template/List")),
    url: "/community/template/list",
    paths: ["/community", "/template", "/List"],
    order: 10800,
		title: "커뮤니티_메뉴 관리",
  },
	ADMIN_BASEFILE_LIST: {
    component: lazy(() => import("@pages/admin/basefile/List")),
    url: "/admin/basefile/list",
    paths: ["/admin", "/basefile", "/List"],
    order: 11100,
		title: "관리자_기초파일 관리",
  },
	ADMIN_CONFIGURATION_LIST: {
    component: lazy(() => import("@pages/admin/configuration/List")),
    url: "/admin/configuration/list",
    paths: ["/admin", "/configuration", "/List"],
    order: 11200,
		title: "관리자_형상관리",
  },
	ADMIN_ENVIRONMENT_ROBOT_LIST: {
    component: lazy(() => import("@pages/admin/environment/robot/List")),
    url: "/admin/environment/robot/list",
    paths: ["/admin", "/environment", "/robot", "/List"],
    order: 11310,
		title: "관리자_환경관리_로봇 환경 관리",
  },
	ADMIN_ENVIRONMENT_WORK_LIST: {
    component: lazy(() => import("@pages/admin/environment/work/List")),
    url: "/admin/environment/work/list",
    paths: ["/admin", "/environment", "/work", "/List"],
    order: 11320,
		title: "관리자_환경관리_업무 환경 관리",
  },
	ADMIN_AUTH_AUTHORITY_LIST: {
    component: lazy(() => import("@pages/admin/auth/authority/List")),
    url: "/admin/auth/authority/list",
    paths: ["/admin", "/auth", "/authority", "/List"],
    order: 11410,
		title: "관리자_권한관리_권한관리",
  },
	ADMIN_AUTH_GROUP_LIST: {
    component: lazy(() => import("@pages/admin/auth/group/List")),
    url: "/admin/auth/group/list",
    paths: ["/admin", "/auth", "/group", "/List"],
    order: 11420,
		title: "관리자_권한관리_작업 그룹 관리",
  },
	ADMIN_AUTH_DEPARTMENTS_LIST: {
    component: lazy(() => import("@pages/admin/auth/departments/List")),
    url: "/admin/auth/departments/list",
    paths: ["/admin", "/auth", "/departments", "/List"],
    order: 11430,
		title: "관리자_권한관리_부서 관리",
  },
	ADMIN_AUTH_USER_LIST: {
    component: lazy(() => import("@pages/admin/auth/user/List")),
    url: "/admin/auth/user/list",
    paths: ["/admin", "/auth", "/user", "/List"],
    order: 11440,
		title: "관리자_권한관리_사용자 관리",
  },
	ADMIN_AUTH_PIC_LIST: {
    component: lazy(() => import("@pages/admin/auth/pic/List")),
    url: "/admin/auth/pic/list",
    paths: ["/admin", "/auth", "/pic", "/List"],
    order: 11450,
		title: "관리자_권한관리_담당자 관리",
  },
	ADMIN_ORGANIZATION_LIST: {
    component: lazy(() => import("@pages/admin/organization/List")),
    url: "/admin/organization/list",
    paths: ["/admin", "/organization", "/List"],
    order: 11500,
		title: "관리자_조직도 관리",
  },
	ADMIN_HOLIDAY_LIST: {
    component: lazy(() => import("@pages/admin/holiday/List")),
    url: "/admin/holiday/list",
    paths: ["/admin", "/holiday", "/List"],
    order: 11600,
		title: "관리자_휴일 관리",
  },
	ADMIN_SYSTEM_COMMONCODE_LIST: {
    component: lazy(() => import("@pages/admin/system/commoncode/List")),
    url: "/admin/system/commoncode/list",
    paths: ["/admin", "/system", "/commoncode", "/List"],
    order: 11710,
		title: "관리자_시스템_시스템 코드 관리",
  },
	ADMIN_SYSTEM_COMMONCONFIG_LIST: {
    component: lazy(() => import("@pages/admin/system/commonconfig/List")),
    url: "/admin/system/commonconfig/list",
    paths: ["/admin", "/system", "/commonconfig", "/List"],
    order: 11720,
		title: "관리자_시스템_시스템 환경 설정",
  },
	ADMIN_BATCH_LIST: {
    component: lazy(() => import("@pages/admin/batch/List")),
    url: "/admin/batch/list",
    paths: ["/admin", "/batch", "/List"],
    order: 11800,
		title: "관리자_배치 작업 관리",
  }
};
export default ROUTES;